# Generated by Django 4.1.3 on 2022-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
